#include <iostream>
#include "node.h"
#include "codegen.h"

extern NBlock* programBlock;  // defined in parser.y
extern int yyparse();         // generated by Bison

int main(int argc, char **argv) {
    std::cout << "Parsing...\n";
    
    if (yyparse() != 0) {
        std::cerr << "Parsing failed.\n";
        return 1;
    }

    std::cout << "Parsing completed.\n";

    CodeGenContext context;
    context.generateCode(*programBlock);
    context.runCode();

    return 0;
}
